FROM python:3.11-alpine AS backend
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
COPY ./backend/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY ./backend /app
RUN chown -R appuser:appgroup /app
USER appuser
EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
