FROM node:20-alpine AS frontend
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm ci --no-optional
COPY ./frontend /app
RUN npm run build
FROM docker.io/library/nginx:alpine AS production
RUN apk add --no-cache libcap
RUN adduser -D -g 'nginx' nginxuser
COPY --from=frontend /app/dist /usr/share/nginx/html
RUN chown -R nginxuser:nginxuser /usr/share/nginx/html
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
